name: Test with Code Coverage
run-name: ${{github.actor}} tests Code Coverage

on:
  workflow_call:
    inputs:
      branch:
        type: string
        required: true
  workflow_dispatch:
    inputs:
      branch:
        type: string
        required: true
        description: Branch name

env:
  XDEBUG_MODE: coverage

jobs:
  test-code-coverage:
    name: Code Coverage Tests
    runs-on: ubuntu-latest
    container:
      image: serversideup/php:8.4-cli-alpine
      options: --user root

    steps:
      - name: Checkout to test
        uses: actions/checkout@v4

      - name: Get cached Composer libraries
        uses: actions/cache@v4
        with:
          key: cache-${{vars.PROJECT}}-composer-${{hashFiles('composer.lock')}}
          path: vendor

      - name: Download artifact with file and folder
        uses: actions/download-artifact@v4
        with:
          name: default-environment-${{vars.PROJECT}}-${{inputs.branch}}

      - name: Install Xdebug
        run: install-php-extensions xdebug

      - name: Run tests
        run: php artisan test --coverage